// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createKey = `-- name: CreateKey :execresult
INSERT INTO keys
    (key_id, seed_fingerprint, alias, curve, algorithm, derivation_path, status, expires_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING key_id, seed_fingerprint, alias, curve, algorithm, derivation_path, status, expires_at
`

type CreateKeyParams struct {
	KeyID           pgtype.UUID
	SeedFingerprint string
	Alias           string
	Curve           string
	Algorithm       string
	DerivationPath  string
	Status          string
	ExpiresAt       pgtype.Timestamp
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createKey,
		arg.KeyID,
		arg.SeedFingerprint,
		arg.Alias,
		arg.Curve,
		arg.Algorithm,
		arg.DerivationPath,
		arg.Status,
		arg.ExpiresAt,
	)
}

const getAllKeys = `-- name: GetAllKeys :many
SELECT key_id, seed_fingerprint, alias, curve, algorithm, derivation_path, status, created_at, updated_at, expires_at
FROM keys
ORDER BY created_at
`

func (q *Queries) GetAllKeys(ctx context.Context) ([]Key, error) {
	rows, err := q.db.Query(ctx, getAllKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Key
	for rows.Next() {
		var i Key
		if err := rows.Scan(
			&i.KeyID,
			&i.SeedFingerprint,
			&i.Alias,
			&i.Curve,
			&i.Algorithm,
			&i.DerivationPath,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKey = `-- name: GetKey :one
SELECT key_id, seed_fingerprint, alias, curve, algorithm, derivation_path, status, created_at, updated_at, expires_at
FROM keys
WHERE key_id = $1
LIMIT 1
`

func (q *Queries) GetKey(ctx context.Context, keyID pgtype.UUID) (Key, error) {
	row := q.db.QueryRow(ctx, getKey, keyID)
	var i Key
	err := row.Scan(
		&i.KeyID,
		&i.SeedFingerprint,
		&i.Alias,
		&i.Curve,
		&i.Algorithm,
		&i.DerivationPath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const setExpiration = `-- name: SetExpiration :exec
UPDATE keys SET expires_at = $2 WHERE key_id = $1
`

type SetExpirationParams struct {
	KeyID     pgtype.UUID
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) SetExpiration(ctx context.Context, arg SetExpirationParams) error {
	_, err := q.db.Exec(ctx, setExpiration, arg.KeyID, arg.ExpiresAt)
	return err
}

const setStatus = `-- name: SetStatus :exec
UPDATE keys SET status = $2 WHERE key_id = $1
`

type SetStatusParams struct {
	KeyID  pgtype.UUID
	Status string
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.Exec(ctx, setStatus, arg.KeyID, arg.Status)
	return err
}
