// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chain struct {
	Coin      string
	Symbol    string
	CoinType  int32
	IsEnabled bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Key struct {
	KeyID           pgtype.UUID
	SeedFingerprint string
	Alias           string
	Curve           string
	Algorithm       string
	DerivationPath  string
	Status          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	ExpiresAt       pgtype.Timestamp
}
