// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	"github.com/LiquidCats/paw/services/litehsm/internal/app/domain/entities"
	"github.com/LiquidCats/paw/services/litehsm/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeychain creates a new instance of MockKeychain. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeychain[Pub any, Priv any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeychain[Pub, Priv] {
	mock := &MockKeychain[Pub, Priv]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeychain is an autogenerated mock type for the Keychain type
type MockKeychain[Pub any, Priv any] struct {
	mock.Mock
}

type MockKeychain_Expecter[Pub any, Priv any] struct {
	mock *mock.Mock
}

func (_m *MockKeychain[Pub, Priv]) EXPECT() *MockKeychain_Expecter[Pub, Priv] {
	return &MockKeychain_Expecter[Pub, Priv]{mock: &_m.Mock}
}

// Derive provides a mock function for the type MockKeychain
func (_mock *MockKeychain[Pub, Priv]) Derive(index entities.Index) (ports.Keychain[Pub, Priv], error) {
	ret := _mock.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for Derive")
	}

	var r0 ports.Keychain[Pub, Priv]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Index) (ports.Keychain[Pub, Priv], error)); ok {
		return returnFunc(index)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Index) ports.Keychain[Pub, Priv]); ok {
		r0 = returnFunc(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.Keychain[Pub, Priv])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Index) error); ok {
		r1 = returnFunc(index)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeychain_Derive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Derive'
type MockKeychain_Derive_Call[Pub any, Priv any] struct {
	*mock.Call
}

// Derive is a helper method to define mock.On call
//   - index entities.Index
func (_e *MockKeychain_Expecter[Pub, Priv]) Derive(index any) *MockKeychain_Derive_Call[Pub, Priv] {
	return &MockKeychain_Derive_Call[Pub, Priv]{Call: _e.mock.On("Derive", index)}
}

func (_c *MockKeychain_Derive_Call[Pub, Priv]) Run(run func(index entities.Index)) *MockKeychain_Derive_Call[Pub, Priv] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Index
		if args[0] != nil {
			arg0 = args[0].(entities.Index)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeychain_Derive_Call[Pub, Priv]) Return(keychain ports.Keychain[Pub, Priv], err error) *MockKeychain_Derive_Call[Pub, Priv] {
	_c.Call.Return(keychain, err)
	return _c
}

func (_c *MockKeychain_Derive_Call[Pub, Priv]) RunAndReturn(run func(index entities.Index) (ports.Keychain[Pub, Priv], error)) *MockKeychain_Derive_Call[Pub, Priv] {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function for the type MockKeychain
func (_mock *MockKeychain[Pub, Priv]) Destroy() {
	_mock.Called()
	return
}

// MockKeychain_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type MockKeychain_Destroy_Call[Pub any, Priv any] struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
func (_e *MockKeychain_Expecter[Pub, Priv]) Destroy() *MockKeychain_Destroy_Call[Pub, Priv] {
	return &MockKeychain_Destroy_Call[Pub, Priv]{Call: _e.mock.On("Destroy")}
}

func (_c *MockKeychain_Destroy_Call[Pub, Priv]) Run(run func()) *MockKeychain_Destroy_Call[Pub, Priv] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeychain_Destroy_Call[Pub, Priv]) Return() *MockKeychain_Destroy_Call[Pub, Priv] {
	_c.Call.Return()
	return _c
}

func (_c *MockKeychain_Destroy_Call[Pub, Priv]) RunAndReturn(run func()) *MockKeychain_Destroy_Call[Pub, Priv] {
	_c.Run(run)
	return _c
}

// PrivateKey provides a mock function for the type MockKeychain
func (_mock *MockKeychain[Pub, Priv]) PrivateKey() *Priv {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrivateKey")
	}

	var r0 *Priv
	if returnFunc, ok := ret.Get(0).(func() *Priv); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Priv)
		}
	}
	return r0
}

// MockKeychain_PrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrivateKey'
type MockKeychain_PrivateKey_Call[Pub any, Priv any] struct {
	*mock.Call
}

// PrivateKey is a helper method to define mock.On call
func (_e *MockKeychain_Expecter[Pub, Priv]) PrivateKey() *MockKeychain_PrivateKey_Call[Pub, Priv] {
	return &MockKeychain_PrivateKey_Call[Pub, Priv]{Call: _e.mock.On("PrivateKey")}
}

func (_c *MockKeychain_PrivateKey_Call[Pub, Priv]) Run(run func()) *MockKeychain_PrivateKey_Call[Pub, Priv] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeychain_PrivateKey_Call[Pub, Priv]) Return(v *Priv) *MockKeychain_PrivateKey_Call[Pub, Priv] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockKeychain_PrivateKey_Call[Pub, Priv]) RunAndReturn(run func() *Priv) *MockKeychain_PrivateKey_Call[Pub, Priv] {
	_c.Call.Return(run)
	return _c
}

// PublicKey provides a mock function for the type MockKeychain
func (_mock *MockKeychain[Pub, Priv]) PublicKey() *Pub {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PublicKey")
	}

	var r0 *Pub
	if returnFunc, ok := ret.Get(0).(func() *Pub); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Pub)
		}
	}
	return r0
}

// MockKeychain_PublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicKey'
type MockKeychain_PublicKey_Call[Pub any, Priv any] struct {
	*mock.Call
}

// PublicKey is a helper method to define mock.On call
func (_e *MockKeychain_Expecter[Pub, Priv]) PublicKey() *MockKeychain_PublicKey_Call[Pub, Priv] {
	return &MockKeychain_PublicKey_Call[Pub, Priv]{Call: _e.mock.On("PublicKey")}
}

func (_c *MockKeychain_PublicKey_Call[Pub, Priv]) Run(run func()) *MockKeychain_PublicKey_Call[Pub, Priv] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockKeychain_PublicKey_Call[Pub, Priv]) Return(v *Pub) *MockKeychain_PublicKey_Call[Pub, Priv] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockKeychain_PublicKey_Call[Pub, Priv]) RunAndReturn(run func() *Pub) *MockKeychain_PublicKey_Call[Pub, Priv] {
	_c.Call.Return(run)
	return _c
}
