// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	"context"
	"time"

	"github.com/LiquidCats/paw/services/litehsm/internal/app/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockKeyManagerRepository creates a new instance of MockKeyManagerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKeyManagerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKeyManagerRepository {
	mock := &MockKeyManagerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKeyManagerRepository is an autogenerated mock type for the KeyManagerRepository type
type MockKeyManagerRepository struct {
	mock.Mock
}

type MockKeyManagerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKeyManagerRepository) EXPECT() *MockKeyManagerRepository_Expecter {
	return &MockKeyManagerRepository_Expecter{mock: &_m.Mock}
}

// CreateKey provides a mock function for the type MockKeyManagerRepository
func (_mock *MockKeyManagerRepository) CreateKey(ctx context.Context, entry entities.KeyEntry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for CreateKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.KeyEntry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyManagerRepository_CreateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKey'
type MockKeyManagerRepository_CreateKey_Call struct {
	*mock.Call
}

// CreateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - entry entities.KeyEntry
func (_e *MockKeyManagerRepository_Expecter) CreateKey(ctx any, entry any) *MockKeyManagerRepository_CreateKey_Call {
	return &MockKeyManagerRepository_CreateKey_Call{Call: _e.mock.On("CreateKey", ctx, entry)}
}

func (_c *MockKeyManagerRepository_CreateKey_Call) Run(run func(ctx context.Context, entry entities.KeyEntry)) *MockKeyManagerRepository_CreateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.KeyEntry
		if args[1] != nil {
			arg1 = args[1].(entities.KeyEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManagerRepository_CreateKey_Call) Return(err error) *MockKeyManagerRepository_CreateKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyManagerRepository_CreateKey_Call) RunAndReturn(run func(ctx context.Context, entry entities.KeyEntry) error) *MockKeyManagerRepository_CreateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllKeys provides a mock function for the type MockKeyManagerRepository
func (_mock *MockKeyManagerRepository) GetAllKeys(ctx context.Context) ([]entities.KeyEntry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllKeys")
	}

	var r0 []entities.KeyEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]entities.KeyEntry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []entities.KeyEntry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.KeyEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyManagerRepository_GetAllKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllKeys'
type MockKeyManagerRepository_GetAllKeys_Call struct {
	*mock.Call
}

// GetAllKeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockKeyManagerRepository_Expecter) GetAllKeys(ctx any) *MockKeyManagerRepository_GetAllKeys_Call {
	return &MockKeyManagerRepository_GetAllKeys_Call{Call: _e.mock.On("GetAllKeys", ctx)}
}

func (_c *MockKeyManagerRepository_GetAllKeys_Call) Run(run func(ctx context.Context)) *MockKeyManagerRepository_GetAllKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockKeyManagerRepository_GetAllKeys_Call) Return(keyEntrys []entities.KeyEntry, err error) *MockKeyManagerRepository_GetAllKeys_Call {
	_c.Call.Return(keyEntrys, err)
	return _c
}

func (_c *MockKeyManagerRepository_GetAllKeys_Call) RunAndReturn(run func(ctx context.Context) ([]entities.KeyEntry, error)) *MockKeyManagerRepository_GetAllKeys_Call {
	_c.Call.Return(run)
	return _c
}

// GetKey provides a mock function for the type MockKeyManagerRepository
func (_mock *MockKeyManagerRepository) GetKey(ctx context.Context, keyID entities.KeyID) (*entities.KeyEntry, error) {
	ret := _mock.Called(ctx, keyID)

	if len(ret) == 0 {
		panic("no return value specified for GetKey")
	}

	var r0 *entities.KeyEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.KeyID) (*entities.KeyEntry, error)); ok {
		return returnFunc(ctx, keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.KeyID) *entities.KeyEntry); ok {
		r0 = returnFunc(ctx, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.KeyEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.KeyID) error); ok {
		r1 = returnFunc(ctx, keyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKeyManagerRepository_GetKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKey'
type MockKeyManagerRepository_GetKey_Call struct {
	*mock.Call
}

// GetKey is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID entities.KeyID
func (_e *MockKeyManagerRepository_Expecter) GetKey(ctx any, keyID any) *MockKeyManagerRepository_GetKey_Call {
	return &MockKeyManagerRepository_GetKey_Call{Call: _e.mock.On("GetKey", ctx, keyID)}
}

func (_c *MockKeyManagerRepository_GetKey_Call) Run(run func(ctx context.Context, keyID entities.KeyID)) *MockKeyManagerRepository_GetKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.KeyID
		if args[1] != nil {
			arg1 = args[1].(entities.KeyID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKeyManagerRepository_GetKey_Call) Return(keyEntry *entities.KeyEntry, err error) *MockKeyManagerRepository_GetKey_Call {
	_c.Call.Return(keyEntry, err)
	return _c
}

func (_c *MockKeyManagerRepository_GetKey_Call) RunAndReturn(run func(ctx context.Context, keyID entities.KeyID) (*entities.KeyEntry, error)) *MockKeyManagerRepository_GetKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetExpiration provides a mock function for the type MockKeyManagerRepository
func (_mock *MockKeyManagerRepository) SetExpiration(ctx context.Context, keyID entities.KeyID, expiresAt *time.Time) error {
	ret := _mock.Called(ctx, keyID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SetExpiration")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.KeyID, *time.Time) error); ok {
		r0 = returnFunc(ctx, keyID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyManagerRepository_SetExpiration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetExpiration'
type MockKeyManagerRepository_SetExpiration_Call struct {
	*mock.Call
}

// SetExpiration is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID entities.KeyID
//   - expiresAt *time.Time
func (_e *MockKeyManagerRepository_Expecter) SetExpiration(ctx any, keyID any, expiresAt any) *MockKeyManagerRepository_SetExpiration_Call {
	return &MockKeyManagerRepository_SetExpiration_Call{Call: _e.mock.On("SetExpiration", ctx, keyID, expiresAt)}
}

func (_c *MockKeyManagerRepository_SetExpiration_Call) Run(run func(ctx context.Context, keyID entities.KeyID, expiresAt *time.Time)) *MockKeyManagerRepository_SetExpiration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.KeyID
		if args[1] != nil {
			arg1 = args[1].(entities.KeyID)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyManagerRepository_SetExpiration_Call) Return(err error) *MockKeyManagerRepository_SetExpiration_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyManagerRepository_SetExpiration_Call) RunAndReturn(run func(ctx context.Context, keyID entities.KeyID, expiresAt *time.Time) error) *MockKeyManagerRepository_SetExpiration_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function for the type MockKeyManagerRepository
func (_mock *MockKeyManagerRepository) SetStatus(ctx context.Context, keyID entities.KeyID, status entities.KeyStatus) error {
	ret := _mock.Called(ctx, keyID, status)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.KeyID, entities.KeyStatus) error); ok {
		r0 = returnFunc(ctx, keyID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKeyManagerRepository_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockKeyManagerRepository_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID entities.KeyID
//   - status entities.KeyStatus
func (_e *MockKeyManagerRepository_Expecter) SetStatus(ctx any, keyID any, status any) *MockKeyManagerRepository_SetStatus_Call {
	return &MockKeyManagerRepository_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, keyID, status)}
}

func (_c *MockKeyManagerRepository_SetStatus_Call) Run(run func(ctx context.Context, keyID entities.KeyID, status entities.KeyStatus)) *MockKeyManagerRepository_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.KeyID
		if args[1] != nil {
			arg1 = args[1].(entities.KeyID)
		}
		var arg2 entities.KeyStatus
		if args[2] != nil {
			arg2 = args[2].(entities.KeyStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKeyManagerRepository_SetStatus_Call) Return(err error) *MockKeyManagerRepository_SetStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKeyManagerRepository_SetStatus_Call) RunAndReturn(run func(ctx context.Context, keyID entities.KeyID, status entities.KeyStatus) error) *MockKeyManagerRepository_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}
