// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	"github.com/awnumar/memguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPassphraseProvider creates a new instance of MockPassphraseProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPassphraseProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPassphraseProvider {
	mock := &MockPassphraseProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPassphraseProvider is an autogenerated mock type for the PassphraseProvider type
type MockPassphraseProvider struct {
	mock.Mock
}

type MockPassphraseProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPassphraseProvider) EXPECT() *MockPassphraseProvider_Expecter {
	return &MockPassphraseProvider_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPassphraseProvider
func (_mock *MockPassphraseProvider) Get(dts string) (*memguard.LockedBuffer, error) {
	ret := _mock.Called(dts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *memguard.LockedBuffer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*memguard.LockedBuffer, error)); ok {
		return returnFunc(dts)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *memguard.LockedBuffer); ok {
		r0 = returnFunc(dts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*memguard.LockedBuffer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(dts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPassphraseProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPassphraseProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - dts string
func (_e *MockPassphraseProvider_Expecter) Get(dts any) *MockPassphraseProvider_Get_Call {
	return &MockPassphraseProvider_Get_Call{Call: _e.mock.On("Get", dts)}
}

func (_c *MockPassphraseProvider_Get_Call) Run(run func(dts string)) *MockPassphraseProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPassphraseProvider_Get_Call) Return(lockedBuffer *memguard.LockedBuffer, err error) *MockPassphraseProvider_Get_Call {
	_c.Call.Return(lockedBuffer, err)
	return _c
}

func (_c *MockPassphraseProvider_Get_Call) RunAndReturn(run func(dts string) (*memguard.LockedBuffer, error)) *MockPassphraseProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockPassphraseProvider
func (_mock *MockPassphraseProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPassphraseProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockPassphraseProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockPassphraseProvider_Expecter) Name() *MockPassphraseProvider_Name_Call {
	return &MockPassphraseProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockPassphraseProvider_Name_Call) Run(run func()) *MockPassphraseProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPassphraseProvider_Name_Call) Return(s string) *MockPassphraseProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPassphraseProvider_Name_Call) RunAndReturn(run func() string) *MockPassphraseProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}
