// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistryRegister creates a new instance of MockRegistryRegister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryRegister[K comparable, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryRegister[K, V] {
	mock := &MockRegistryRegister[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryRegister is an autogenerated mock type for the RegistryRegister type
type MockRegistryRegister[K comparable, V any] struct {
	mock.Mock
}

type MockRegistryRegister_Expecter[K comparable, V any] struct {
	mock *mock.Mock
}

func (_m *MockRegistryRegister[K, V]) EXPECT() *MockRegistryRegister_Expecter[K, V] {
	return &MockRegistryRegister_Expecter[K, V]{mock: &_m.Mock}
}

// Register provides a mock function for the type MockRegistryRegister
func (_mock *MockRegistryRegister[K, V]) Register(key K, value V) {
	_mock.Called(key, value)
	return
}

// MockRegistryRegister_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegistryRegister_Register_Call[K comparable, V any] struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - key K
//   - value V
func (_e *MockRegistryRegister_Expecter[K, V]) Register(key any, value any) *MockRegistryRegister_Register_Call[K, V] {
	return &MockRegistryRegister_Register_Call[K, V]{Call: _e.mock.On("Register", key, value)}
}

func (_c *MockRegistryRegister_Register_Call[K, V]) Run(run func(key K, value V)) *MockRegistryRegister_Register_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		var arg1 V
		if args[1] != nil {
			arg1 = args[1].(V)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistryRegister_Register_Call[K, V]) Return() *MockRegistryRegister_Register_Call[K, V] {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistryRegister_Register_Call[K, V]) RunAndReturn(run func(key K, value V)) *MockRegistryRegister_Register_Call[K, V] {
	_c.Run(run)
	return _c
}
