// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistryGetter creates a new instance of MockRegistryGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryGetter[K comparable, V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryGetter[K, V] {
	mock := &MockRegistryGetter[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryGetter is an autogenerated mock type for the RegistryGetter type
type MockRegistryGetter[K comparable, V any] struct {
	mock.Mock
}

type MockRegistryGetter_Expecter[K comparable, V any] struct {
	mock *mock.Mock
}

func (_m *MockRegistryGetter[K, V]) EXPECT() *MockRegistryGetter_Expecter[K, V] {
	return &MockRegistryGetter_Expecter[K, V]{mock: &_m.Mock}
}

// All provides a mock function for the type MockRegistryGetter
func (_mock *MockRegistryGetter[K, V]) All() []V {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []V
	if returnFunc, ok := ret.Get(0).(func() []V); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]V)
		}
	}
	return r0
}

// MockRegistryGetter_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockRegistryGetter_All_Call[K comparable, V any] struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockRegistryGetter_Expecter[K, V]) All() *MockRegistryGetter_All_Call[K, V] {
	return &MockRegistryGetter_All_Call[K, V]{Call: _e.mock.On("All")}
}

func (_c *MockRegistryGetter_All_Call[K, V]) Run(run func()) *MockRegistryGetter_All_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistryGetter_All_Call[K, V]) Return(vs []V) *MockRegistryGetter_All_Call[K, V] {
	_c.Call.Return(vs)
	return _c
}

func (_c *MockRegistryGetter_All_Call[K, V]) RunAndReturn(run func() []V) *MockRegistryGetter_All_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRegistryGetter
func (_mock *MockRegistryGetter[K, V]) Get(key K) (V, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(K) (V, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(K) V); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(K) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRegistryGetter_Get_Call[K comparable, V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key K
func (_e *MockRegistryGetter_Expecter[K, V]) Get(key any) *MockRegistryGetter_Get_Call[K, V] {
	return &MockRegistryGetter_Get_Call[K, V]{Call: _e.mock.On("Get", key)}
}

func (_c *MockRegistryGetter_Get_Call[K, V]) Run(run func(key K)) *MockRegistryGetter_Get_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistryGetter_Get_Call[K, V]) Return(v V, err error) *MockRegistryGetter_Get_Call[K, V] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRegistryGetter_Get_Call[K, V]) RunAndReturn(run func(key K) (V, error)) *MockRegistryGetter_Get_Call[K, V] {
	_c.Call.Return(run)
	return _c
}
