// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	"github.com/LiquidCats/paw/services/litehsm/internal/app/domain/entities"
	"github.com/awnumar/memguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSealer creates a new instance of MockSealer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSealer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSealer {
	mock := &MockSealer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSealer is an autogenerated mock type for the Sealer type
type MockSealer struct {
	mock.Mock
}

type MockSealer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSealer) EXPECT() *MockSealer_Expecter {
	return &MockSealer_Expecter{mock: &_m.Mock}
}

// Seal provides a mock function for the type MockSealer
func (_mock *MockSealer) Seal(passphrase *memguard.Enclave, data *memguard.LockedBuffer) (*entities.Envelope, error) {
	ret := _mock.Called(passphrase, data)

	if len(ret) == 0 {
		panic("no return value specified for Seal")
	}

	var r0 *entities.Envelope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*memguard.Enclave, *memguard.LockedBuffer) (*entities.Envelope, error)); ok {
		return returnFunc(passphrase, data)
	}
	if returnFunc, ok := ret.Get(0).(func(*memguard.Enclave, *memguard.LockedBuffer) *entities.Envelope); ok {
		r0 = returnFunc(passphrase, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Envelope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*memguard.Enclave, *memguard.LockedBuffer) error); ok {
		r1 = returnFunc(passphrase, data)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSealer_Seal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seal'
type MockSealer_Seal_Call struct {
	*mock.Call
}

// Seal is a helper method to define mock.On call
//   - passphrase *memguard.Enclave
//   - data *memguard.LockedBuffer
func (_e *MockSealer_Expecter) Seal(passphrase any, data any) *MockSealer_Seal_Call {
	return &MockSealer_Seal_Call{Call: _e.mock.On("Seal", passphrase, data)}
}

func (_c *MockSealer_Seal_Call) Run(run func(passphrase *memguard.Enclave, data *memguard.LockedBuffer)) *MockSealer_Seal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *memguard.Enclave
		if args[0] != nil {
			arg0 = args[0].(*memguard.Enclave)
		}
		var arg1 *memguard.LockedBuffer
		if args[1] != nil {
			arg1 = args[1].(*memguard.LockedBuffer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSealer_Seal_Call) Return(envelope *entities.Envelope, err error) *MockSealer_Seal_Call {
	_c.Call.Return(envelope, err)
	return _c
}

func (_c *MockSealer_Seal_Call) RunAndReturn(run func(passphrase *memguard.Enclave, data *memguard.LockedBuffer) (*entities.Envelope, error)) *MockSealer_Seal_Call {
	_c.Call.Return(run)
	return _c
}
