// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	"context"

	"github.com/LiquidCats/paw/services/litehsm/internal/app/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxManager creates a new instance of MockTxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxManager {
	mock := &MockTxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxManager is an autogenerated mock type for the TxManager type
type MockTxManager struct {
	mock.Mock
}

type MockTxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxManager) EXPECT() *MockTxManager_Expecter {
	return &MockTxManager_Expecter{mock: &_m.Mock}
}

// Transactional provides a mock function for the type MockTxManager
func (_mock *MockTxManager) Transactional(ctx context.Context, callback ports.TxCallback) error {
	ret := _mock.Called(ctx, callback)

	if len(ret) == 0 {
		panic("no return value specified for Transactional")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.TxCallback) error); ok {
		r0 = returnFunc(ctx, callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTxManager_Transactional_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transactional'
type MockTxManager_Transactional_Call struct {
	*mock.Call
}

// Transactional is a helper method to define mock.On call
//   - ctx context.Context
//   - callback ports.TxCallback
func (_e *MockTxManager_Expecter) Transactional(ctx any, callback any) *MockTxManager_Transactional_Call {
	return &MockTxManager_Transactional_Call{Call: _e.mock.On("Transactional", ctx, callback)}
}

func (_c *MockTxManager_Transactional_Call) Run(run func(ctx context.Context, callback ports.TxCallback)) *MockTxManager_Transactional_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.TxCallback
		if args[1] != nil {
			arg1 = args[1].(ports.TxCallback)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTxManager_Transactional_Call) Return(err error) *MockTxManager_Transactional_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTxManager_Transactional_Call) RunAndReturn(run func(ctx context.Context, callback ports.TxCallback) error) *MockTxManager_Transactional_Call {
	_c.Call.Return(run)
	return _c
}
