// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package litehsm

import (
	"github.com/LiquidCats/paw/services/litehsm/internal/app/domain/entities"
	"github.com/awnumar/memguard"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsealer creates a new instance of MockUnsealer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsealer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsealer {
	mock := &MockUnsealer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsealer is an autogenerated mock type for the Unsealer type
type MockUnsealer struct {
	mock.Mock
}

type MockUnsealer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsealer) EXPECT() *MockUnsealer_Expecter {
	return &MockUnsealer_Expecter{mock: &_m.Mock}
}

// Unseal provides a mock function for the type MockUnsealer
func (_mock *MockUnsealer) Unseal(envelope *entities.Envelope, passphrase *memguard.Enclave) (*memguard.Enclave, error) {
	ret := _mock.Called(envelope, passphrase)

	if len(ret) == 0 {
		panic("no return value specified for Unseal")
	}

	var r0 *memguard.Enclave
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.Envelope, *memguard.Enclave) (*memguard.Enclave, error)); ok {
		return returnFunc(envelope, passphrase)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.Envelope, *memguard.Enclave) *memguard.Enclave); ok {
		r0 = returnFunc(envelope, passphrase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*memguard.Enclave)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.Envelope, *memguard.Enclave) error); ok {
		r1 = returnFunc(envelope, passphrase)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUnsealer_Unseal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unseal'
type MockUnsealer_Unseal_Call struct {
	*mock.Call
}

// Unseal is a helper method to define mock.On call
//   - envelope *entities.Envelope
//   - passphrase *memguard.Enclave
func (_e *MockUnsealer_Expecter) Unseal(envelope any, passphrase any) *MockUnsealer_Unseal_Call {
	return &MockUnsealer_Unseal_Call{Call: _e.mock.On("Unseal", envelope, passphrase)}
}

func (_c *MockUnsealer_Unseal_Call) Run(run func(envelope *entities.Envelope, passphrase *memguard.Enclave)) *MockUnsealer_Unseal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Envelope
		if args[0] != nil {
			arg0 = args[0].(*entities.Envelope)
		}
		var arg1 *memguard.Enclave
		if args[1] != nil {
			arg1 = args[1].(*memguard.Enclave)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUnsealer_Unseal_Call) Return(enclave *memguard.Enclave, err error) *MockUnsealer_Unseal_Call {
	_c.Call.Return(enclave, err)
	return _c
}

func (_c *MockUnsealer_Unseal_Call) RunAndReturn(run func(envelope *entities.Envelope, passphrase *memguard.Enclave) (*memguard.Enclave, error)) *MockUnsealer_Unseal_Call {
	_c.Call.Return(run)
	return _c
}
